### ISSUE TITLE
Application Review Template (Just a Test)

### ISSUE THREAD

**Issue by leogopal** [WordPress/Community#59]
## Details

- Content type (Meetup)
 This can and should also be a label

- Content title (City name, event name)
 Could be helpful to add this to the title

- Topic Description: 

- Tracker link: 
- HelpScount link: 

## Next steps
- Please assign the issue to the team member
- Team members will perform the task on the tracker and HS as indicated on the handbook 
- Once the task is completed, the team member can mark the issue as fixed

## Useful Resources
- Application Review: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/
- Most Common Cases: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#most-common-cases-quick-step-by-step-guide
- Video tutorial: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#quick-step-by-step-video-tutorial-for-application-review

**Comment by peiraisotta** [comment]
Thank you so much, @leogopal !
