### ISSUE TITLE
WordCamp San José, Costa Rica 

### ISSUE THREAD

**Issue by lupoair** [WordPress/Community#63]
## Details

> NOTE: Always use HelpScout or the Tracker for any notes/updates specific to the application.
Github is to be used for status, assignment, progress, and other task/project updates and visibility.

- Content type (Meetup, WordCamp, other event type): WordCamp
- Content title (City name, event name): San José, Costa Rica
- Topic description: [WordCamp San José, Costa Rica](https://central.wordcamp.org/wp-admin/post.php?post=5138356&action=edit)
- [Tracker link](https://central.wordcamp.org/wp-admin/post.php?post=5138356&action=edit)
- [HS link](https://secure.helpscout.net/conversation/2478060198/171177/)

## Next steps
- Please assign the issue to the team member and make sure to mark the issue ```To Do```
- Assignee (Team Member) will mark the issue as ```In Progress``` and perform the vetting taks on the tracker and HS as indicated on the handbook
- Once the vetting is completed marke the issue as ```In Review```
- Once pair reviewing is done ```Close``` the issue

## Public vs Private

- Use comments for questions about the process and changes or to indicate delays, holding situation.
- Avoid discussing the community or the organiser in comments on Github. Even if there are doubts about some applications.
- We do not post vetting notes publicly and ensure such notes are strictly in the tracker or HelpScout.

## Useful Resources
- Application Review: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/
- Most Common Cases: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#most-common-cases-quick-step-by-step-guide
- Video tutorial: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#quick-step-by-step-video-tutorial-for-application-review

**Comment by webtechpooja** [comment]
An email was sent to the applicant to get more information. Waiting for their response.

**Comment by devinmaeztri** [comment]
Hello, @lumicliment, since you vetted the application and the application has been followed up. Could you please help close the issue? Thank you!

**Comment by lumicliment** [comment]
Issue closed.
