### ISSUE TITLE
[WordCamp]: St. John’s, Newfoundland Application

### ISSUE THREAD

**Issue by bombaypirate** [WordPress/Community#66]
### WordCamp City, Event Name

WordCamp St. John’s, Newfoundland 

### WordCamp Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=5259593&action=edit

### WordCamp HelpScout Link

https://secure.helpscout.net/conversation/2488160776/171672?folderId=1197065

**Comment by webtechpooja** [comment]
I vetted this application and left my notes in private comment on event tracker. Looking for more feedback on this, so asked question in Program supporter slack group and will update here once I have more information on this.

**Comment by webtechpooja** [comment]
I have sent email to applicant to active Meetup group first and then apply to WordCamp, more info is in email.
