### ISSUE TITLE
[Meetup]: Hutchinson

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community#70]
### Meetup City, Event Name

Hutchinson

### Meetup Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=4956076&action=edit

### Meetup HelpScout Link

https://secure.helpscout.net/conversation/2463136083/170494/

**Comment by devinmaeztri** [comment]
Ahmed Chaion is vetting this application.

**Comment by chaion07** [comment]
This meetup chapter is approve and live now https://www.meetup.com/hutchinson-wordpress-meetup/
They recently had their first event: https://www.meetup.com/hutchinson-wordpress-meetup/events/298916163/

**Comment by devinmaeztri** [comment]
Thank you @chaion07! 🎉
