### ISSUE TITLE
[Meetup]: Ilorin

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Community#82]
### Meetup City or Event Name

Ilorin, Kwara, NG

### Meetup Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=5117865&action=edit

### Meetup HelpScout Link

https://secure.helpscout.net/conversation/2475950143/171038

**Comment by flopez1977** [comment]
I can't auto assign to me

**Comment by flopez1977** [comment]
Added my notes in event tracker and sent an email to applicant for orientation.
