### ISSUE TITLE
[WordCamp]: Lagos, Nigeria

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Community#86]
### WordCamp City, Event Name

Lagos

### WordCamp Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=5605260&action=edit

### WordCamp HelpScout Link

https://secure.helpscout.net/conversation/2518985014/173652/

**Comment by devinmaeztri** [comment]
The application is declined. Cate has sent the email to notify and offer a help.
