### ISSUE TITLE
[WordCamp] Kolkata, India

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Community#92]
### WordCamp City, Event Name

Kolkata

### WordCamp Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=6200199&action=edit

**Comment by nukaga** [comment]
WordCamp HelpScout Link
https://secure.helpscout.net/conversation/2571060522/176045/

**Comment by devinmaeztri** [comment]
Hello, @nukaga! Since the vetting process has been completed, would you be willing to update the status and close the issue? Thank you :)
